server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.232:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: emp-service

logging:
  level:
    org.exampledriven.eureka.customer.shared.CustomerServiceFeignClient: FULL
    org.exampledriven.eureka: DEBUG